### PR TITLE
Elemental3 upgrade

### PR DESCRIPTION
**Pull request by realityforge**
Hi,

A couple of people asked me about your webtack example so I decided to upgrade it to the current version that I am experimenting with. Hope you don't mind about that :)

Along the way I noticed a few other oddities and "fixed" them. Namely:
* Replaced `java.util.logging.Logger` with regular browser logging (i.e. `Console.log(...)`
* Added `@JsType` annotations to `Product` so that the representation is stable over time
* Removed fields that were not necessary as they could be derived from the event objects
* Changed the way feature detection was accomplished with what I traditionally recommend

HTH

### CODE REVIEW

**Comment by lofidewanto** [comment]
@realityforge A question: why should we export the Product as a JS object? I'm not sure, whether this is a must?

Thanks a lot for the MR / PR!

**Comment by lofidewanto** [comment]
Ah, you said this: "Added @JsType annotations to Product so that the representation is stable over time".

Why is this important, because the object is never getting accessed from "outside" actually... just curious 😉

Thanks.

**Comment by realityforge** [comment]
If `@JsType` is not added then the shape of the object can change between different compiles of GWT based on optimization levels and/or ordering of inputs into GWT compile (which can be platform dependent). This means that you could not safely use the same product representation between different versions of the compiled app.

With the type annotations the `id` will always be represented by a `id` json key. If you need to change the storage format you do so deliberately rather than accidentally.

If that makes sense.

**Comment by lofidewanto** [comment]
Thanks for the info. 

If I need to use the same class also on the server, then I need to add the JsInterop lib on the server project. Is it worth it to do this?

**Comment by realityforge** [comment]
No idea - that is up to you :) I don't see jsinterop annotations as being too onerous but I can understand not wanting client-side stuff polluting the server.

At my workplace we use a "model driven architecture" style approach and define the entity as a model element and then generate completely separate representations for client and server and thus never really run into this issue. Even our transport layers are generated thus the only things we share between the client and server and classes containing constants.

**Comment by lofidewanto** [comment]
Thanks for the insight... yes with MDSD / MDA this would be no problem... I have also used MDSD / MDA, my own generator: https://github.com/crowdcode-de/KissMDA

**Pull request merged**
